# Fetches the Google Fonts woff2 files we use and writes them to
# public/fonts/, along with a self-contained fonts.css that references
# them via relative paths. Run this once; the committed files travel
# with the app so the desktop/Android builds ship fully offline.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts/fetch-fonts.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'public\fonts'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# Google Fonts serves different CSS depending on User-Agent. We request
# the modern woff2-flavoured stylesheet (Chrome UA) for the exact
# families + weights + styles the app uses.
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
$cssUrl = 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;0,9..144,700&family=Geist:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap'

# Use a plain WebClient — Invoke-WebRequest in legacy Windows PowerShell
# lazily initialises an IE parsing engine which fails on stripped-down
# systems. WebClient is older/uglier but has no such dependency and
# works everywhere PowerShell ships.
function Get-Web($url) {
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    $wc = New-Object System.Net.WebClient
    $wc.Headers.Add('User-Agent', $ua)
    return $wc
}

Write-Host "Fetching font CSS..."
$wc = Get-Web $cssUrl
$css = $wc.DownloadString($cssUrl)
$wc.Dispose()

# Pick out every unique gstatic woff2 URL, download each one, and
# rewrite the CSS to point at the local copy under /fonts/.
$urls = [regex]::Matches($css, 'https://fonts\.gstatic\.com/[^)]+\.woff2') |
    ForEach-Object { $_.Value } | Sort-Object -Unique

Write-Host "Found $($urls.Count) unique woff2 files"

$localCss = $css
foreach ($u in $urls) {
    # Deterministic local name derived from the URL hash so re-runs
    # don't create duplicate files and the CSS diff stays minimal.
    $hash = [System.BitConverter]::ToString(
        [System.Security.Cryptography.SHA1]::Create().ComputeHash(
            [System.Text.Encoding]::UTF8.GetBytes($u)
        )
    ).Replace('-', '').Substring(0, 12).ToLower()
    $fileName = "$hash.woff2"
    $dest = Join-Path $outDir $fileName

    if (-not (Test-Path $dest)) {
        Write-Host "  download $fileName"
        $wc = Get-Web $u
        $wc.DownloadFile($u, $dest)
        $wc.Dispose()
    } else {
        Write-Host "  cached   $fileName"
    }

    # Relative path from the CSS (served at /fonts/fonts.css) to the
    # woff2 (served at /fonts/<hash>.woff2) is just the filename.
    $localCss = $localCss.Replace($u, $fileName)
}

$cssPath = Join-Path $outDir 'fonts.css'
$header = "/* Auto-generated by scripts/fetch-fonts.ps1 -- do not edit.`n" +
          "   Source: $cssUrl`n" +
          "   All referenced .woff2 files live next to this file. */`n`n"
# Windows PowerShell's -Encoding UTF8 writes a BOM which some older
# CSS parsers choke on. Use .NET directly to write a plain UTF-8 file
# without the byte-order mark.
[System.IO.File]::WriteAllText(
    $cssPath,
    $header + $localCss,
    (New-Object System.Text.UTF8Encoding $false)
)
Write-Host "Wrote $cssPath"
